// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
 await Firebase.initializeApp(
   options: DefaultFirebaseOptions.currentPlatform,
);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOV_KJgWAonvFhI_NH_HQtbuRX7kVyVVE',
    appId: '1:247419912734:web:1cc5c91b5043492fb3e40f',
    messagingSenderId: '247419912734',
    projectId: 'leave-8d0f6',
    authDomain: 'leave-8d0f6.firebaseapp.com',
    storageBucket: 'leave-8d0f6.appspot.com',
    measurementId: 'G-XKM2NRF55R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUEa79wovZehuq6lsxSc7xVQYjGFlG8d4',
    appId: '1:247419912734:android:eb05c2a096cbfa59b3e40f',
    messagingSenderId: '247419912734',
    projectId: 'leave-8d0f6',
    storageBucket: 'leave-8d0f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZxq_pi4MPn5Bc25SADZOQ3HGXcET0cuY',
    appId: '1:247419912734:ios:0b13bfcc1dee5369b3e40f',
    messagingSenderId: '247419912734',
    projectId: 'leave-8d0f6',
    storageBucket: 'leave-8d0f6.appspot.com',
    iosBundleId: 'com.example.myLaptopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZxq_pi4MPn5Bc25SADZOQ3HGXcET0cuY',
    appId: '1:247419912734:ios:0b13bfcc1dee5369b3e40f',
    messagingSenderId: '247419912734',
    projectId: 'leave-8d0f6',
    storageBucket: 'leave-8d0f6.appspot.com',
    iosBundleId: 'com.example.myLaptopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOV_KJgWAonvFhI_NH_HQtbuRX7kVyVVE',
    appId: '1:247419912734:web:ac16bb5d0995a14eb3e40f',
    messagingSenderId: '247419912734',
    projectId: 'leave-8d0f6',
    authDomain: 'leave-8d0f6.firebaseapp.com',
    storageBucket: 'leave-8d0f6.appspot.com',
    measurementId: 'G-BXXT2WNT4Z',
  );

}